# -*- coding: utf-8 -*-
# Generated by the protocol buffer compiler.  DO NOT EDIT!
# source: ctpview-trader.proto

from google.protobuf import descriptor as _descriptor
from google.protobuf import message as _message
from google.protobuf import reflection as _reflection
from google.protobuf import symbol_database as _symbol_database
# @@protoc_insertion_point(imports)

_sym_db = _symbol_database.Default()




DESCRIPTOR = _descriptor.FileDescriptor(
  name='ctpview-trader.proto',
  package='ctpview_trader',
  syntax='proto3',
  serialized_options=None,
  create_key=_descriptor._internal_create_key,
  serialized_pb=b'\n\x14\x63tpview-trader.proto\x12\x0e\x63tpview_trader\"O\n\x07message\x12\x35\n\rlogin_control\x18\x01 \x01(\x0b\x32\x1c.ctpview_trader.LoginControlH\x00\x42\r\n\x0bMessageType\"t\n\x0cLoginControl\x12\x35\n\x07\x63ommand\x18\x01 \x01(\x0e\x32$.ctpview_trader.LoginControl.Command\"-\n\x07\x43ommand\x12\x0b\n\x07reserve\x10\x00\x12\t\n\x05login\x10\x01\x12\n\n\x06logout\x10\x02\x62\x06proto3'
)



_LOGINCONTROL_COMMAND = _descriptor.EnumDescriptor(
  name='Command',
  full_name='ctpview_trader.LoginControl.Command',
  filename=None,
  file=DESCRIPTOR,
  create_key=_descriptor._internal_create_key,
  values=[
    _descriptor.EnumValueDescriptor(
      name='reserve', index=0, number=0,
      serialized_options=None,
      type=None,
      create_key=_descriptor._internal_create_key),
    _descriptor.EnumValueDescriptor(
      name='login', index=1, number=1,
      serialized_options=None,
      type=None,
      create_key=_descriptor._internal_create_key),
    _descriptor.EnumValueDescriptor(
      name='logout', index=2, number=2,
      serialized_options=None,
      type=None,
      create_key=_descriptor._internal_create_key),
  ],
  containing_type=None,
  serialized_options=None,
  serialized_start=192,
  serialized_end=237,
)
_sym_db.RegisterEnumDescriptor(_LOGINCONTROL_COMMAND)


_MESSAGE = _descriptor.Descriptor(
  name='message',
  full_name='ctpview_trader.message',
  filename=None,
  file=DESCRIPTOR,
  containing_type=None,
  create_key=_descriptor._internal_create_key,
  fields=[
    _descriptor.FieldDescriptor(
      name='login_control', full_name='ctpview_trader.message.login_control', index=0,
      number=1, type=11, cpp_type=10, label=1,
      has_default_value=False, default_value=None,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR,  create_key=_descriptor._internal_create_key),
  ],
  extensions=[
  ],
  nested_types=[],
  enum_types=[
  ],
  serialized_options=None,
  is_extendable=False,
  syntax='proto3',
  extension_ranges=[],
  oneofs=[
    _descriptor.OneofDescriptor(
      name='MessageType', full_name='ctpview_trader.message.MessageType',
      index=0, containing_type=None,
      create_key=_descriptor._internal_create_key,
    fields=[]),
  ],
  serialized_start=40,
  serialized_end=119,
)


_LOGINCONTROL = _descriptor.Descriptor(
  name='LoginControl',
  full_name='ctpview_trader.LoginControl',
  filename=None,
  file=DESCRIPTOR,
  containing_type=None,
  create_key=_descriptor._internal_create_key,
  fields=[
    _descriptor.FieldDescriptor(
      name='command', full_name='ctpview_trader.LoginControl.command', index=0,
      number=1, type=14, cpp_type=8, label=1,
      has_default_value=False, default_value=0,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR,  create_key=_descriptor._internal_create_key),
  ],
  extensions=[
  ],
  nested_types=[],
  enum_types=[
    _LOGINCONTROL_COMMAND,
  ],
  serialized_options=None,
  is_extendable=False,
  syntax='proto3',
  extension_ranges=[],
  oneofs=[
  ],
  serialized_start=121,
  serialized_end=237,
)

_MESSAGE.fields_by_name['login_control'].message_type = _LOGINCONTROL
_MESSAGE.oneofs_by_name['MessageType'].fields.append(
  _MESSAGE.fields_by_name['login_control'])
_MESSAGE.fields_by_name['login_control'].containing_oneof = _MESSAGE.oneofs_by_name['MessageType']
_LOGINCONTROL.fields_by_name['command'].enum_type = _LOGINCONTROL_COMMAND
_LOGINCONTROL_COMMAND.containing_type = _LOGINCONTROL
DESCRIPTOR.message_types_by_name['message'] = _MESSAGE
DESCRIPTOR.message_types_by_name['LoginControl'] = _LOGINCONTROL
_sym_db.RegisterFileDescriptor(DESCRIPTOR)

message = _reflection.GeneratedProtocolMessageType('message', (_message.Message,), {
  'DESCRIPTOR' : _MESSAGE,
  '__module__' : 'ctpview_trader_pb2'
  # @@protoc_insertion_point(class_scope:ctpview_trader.message)
  })
_sym_db.RegisterMessage(message)

LoginControl = _reflection.GeneratedProtocolMessageType('LoginControl', (_message.Message,), {
  'DESCRIPTOR' : _LOGINCONTROL,
  '__module__' : 'ctpview_trader_pb2'
  # @@protoc_insertion_point(class_scope:ctpview_trader.LoginControl)
  })
_sym_db.RegisterMessage(LoginControl)


# @@protoc_insertion_point(module_scope)
