# -*- coding: utf-8 -*-
# Generated by the protocol buffer compiler.  DO NOT EDIT!
# source: ctpview-market.proto
"""Generated protocol buffer code."""
from google.protobuf.internal import builder as _builder
from google.protobuf import descriptor as _descriptor
from google.protobuf import descriptor_pool as _descriptor_pool
from google.protobuf import symbol_database as _symbol_database
# @@protoc_insertion_point(imports)

_sym_db = _symbol_database.Default()




DESCRIPTOR = _descriptor_pool.Default().AddSerializedFile(b'\n\x14\x63tpview-market.proto\x12\x0e\x63tpview_market\"\xbe\x02\n\x07message\x12\x35\n\rlogin_control\x18\x01 \x01(\x0b\x32\x1c.ctpview_market.LoginControlH\x00\x12\x39\n\x0b\x63heck_alive\x18\x02 \x01(\x0b\x32\".ctpview_market.CheckStrategyAliveH\x00\x12\x35\n\rblock_control\x18\x03 \x01(\x0b\x32\x1c.ctpview_market.BlockControlH\x00\x12\x35\n\rbug_injection\x18\x04 \x01(\x0b\x32\x1c.ctpview_market.BugInjectionH\x00\x12\x44\n\x15simulate_market_state\x18\x05 \x01(\x0b\x32#.ctpview_market.SimulateMarketStateH\x00\x42\r\n\x0bMessageType\"t\n\x0cLoginControl\x12\x35\n\x07\x63ommand\x18\x01 \x01(\x0e\x32$.ctpview_market.LoginControl.Command\"-\n\x07\x43ommand\x12\x0b\n\x07reserve\x10\x00\x12\t\n\x05login\x10\x01\x12\n\n\x06logout\x10\x02\"#\n\x12\x43heckStrategyAlive\x12\r\n\x05\x63heck\x18\x01 \x01(\t\"u\n\x0c\x42lockControl\x12\x35\n\x07\x63ommand\x18\x01 \x01(\x0e\x32$.ctpview_market.BlockControl.Command\".\n\x07\x43ommand\x12\x0b\n\x07reserve\x10\x00\x12\t\n\x05\x62lock\x10\x01\x12\x0b\n\x07unblock\x10\x02\"\xd4\x01\n\x13SimulateMarketState\x12\x45\n\x0cmarket_state\x18\x01 \x01(\x0e\x32/.ctpview_market.SimulateMarketState.MarketState\x12\x0c\n\x04\x64\x61te\x18\x02 \x01(\t\x12\x0e\n\x06target\x18\x03 \x01(\t\"X\n\x0bMarketState\x12\x0b\n\x07reserve\x10\x00\x12\x0c\n\x08\x64\x61y_open\x10\x01\x12\r\n\tday_close\x10\x02\x12\x0e\n\nnight_open\x10\x03\x12\x0f\n\x0bnight_close\x10\x04\"w\n\x0c\x42ugInjection\x12\x38\n\x04type\x18\x01 \x01(\x0e\x32*.ctpview_market.BugInjection.InjectionType\"-\n\rInjectionType\x12\x0b\n\x07reserve\x10\x00\x12\x0f\n\x0b\x64ouble_free\x10\x01\x62\x06proto3')

_builder.BuildMessageAndEnumDescriptors(DESCRIPTOR, globals())
_builder.BuildTopDescriptorsAndMessages(DESCRIPTOR, 'ctpview_market_pb2', globals())
if _descriptor._USE_C_DESCRIPTORS == False:

  DESCRIPTOR._options = None
  _MESSAGE._serialized_start=41
  _MESSAGE._serialized_end=359
  _LOGINCONTROL._serialized_start=361
  _LOGINCONTROL._serialized_end=477
  _LOGINCONTROL_COMMAND._serialized_start=432
  _LOGINCONTROL_COMMAND._serialized_end=477
  _CHECKSTRATEGYALIVE._serialized_start=479
  _CHECKSTRATEGYALIVE._serialized_end=514
  _BLOCKCONTROL._serialized_start=516
  _BLOCKCONTROL._serialized_end=633
  _BLOCKCONTROL_COMMAND._serialized_start=587
  _BLOCKCONTROL_COMMAND._serialized_end=633
  _SIMULATEMARKETSTATE._serialized_start=636
  _SIMULATEMARKETSTATE._serialized_end=848
  _SIMULATEMARKETSTATE_MARKETSTATE._serialized_start=760
  _SIMULATEMARKETSTATE_MARKETSTATE._serialized_end=848
  _BUGINJECTION._serialized_start=850
  _BUGINJECTION._serialized_end=969
  _BUGINJECTION_INJECTIONTYPE._serialized_start=924
  _BUGINJECTION_INJECTIONTYPE._serialized_end=969
# @@protoc_insertion_point(module_scope)
